### ISSUE TITLE
Mounting the component in enzyme throws an error

### ISSUE THREAD

**Issue by graphan** [andreypopp/react-textarea-autosize#177] opened 2017-09-05 09:52 UTC
```console
TypeError: clearNextFrameAction is not a function

      at TextareaAutosize._clearNextFrame (node_modules/react-textarea-autosize/lib/index.js:377:5)
      at TextareaAutosize.componentWillReceiveProps (node_modules/react-textarea-autosize/lib/index.js:358:10)
```

**Comment by Andarist** [comment] 2017-09-08 12:47
Could u share a repository with reproduced issue?

**Comment by bryanrsmith** [comment] 2017-09-18 21:57
I had the same problem. The issue is that react-textarea-autosize [detects its environment](https://github.com/andreypopp/react-textarea-autosize/blob/caf00a47fb1cf403ed1874cae9e188d16957051b/src/isBrowser.js#L1) when you import it, and I wasn't setting up the `window` and `document` JSDOM globals until later in my test script. So, react-textarea-autosize thought it was not running in a browser, and then crashesd when it got mounted. I worked around the error by importing a file that set up JSDOM just before importing the React module that uses react-textarea-autosize. So, my test file's imports now look something like this:

```js
import 'mocha';
import React from 'react';
import { mount } from 'enzyme';
import expect from 'expect';
import './setUpDOM';
import './MyReactComponent';
```

setUpDOM.js initializes `global.window`, `global.document`, and `global.navigator` to some JSDOM instances so they're available when the React component is imported.

**Comment by Andarist** [comment] 2017-09-18 22:37
@bryanrsmith thanks for sharing your findings, could u describe ur issue in more details though? On what line of the code did `react-textarea-autosize` crash for u? What was its internal state?

**Comment by bryanrsmith** [comment] 2017-09-18 22:49
1. `isBrowser` is initialized to `false` on [line 1](https://github.com/andreypopp/react-textarea-autosize/blob/caf00a47fb1cf403ed1874cae9e188d16957051b/src/calculateNodeHeight.js#L1)
1. The test fails and `hiddenTextarea` is assigned to `false` on [line 3](https://github.com/andreypopp/react-textarea-autosize/blob/caf00a47fb1cf403ed1874cae9e188d16957051b/src/calculateNodeHeight.js#L3)
1. The crash happens on [line 66](https://github.com/andreypopp/react-textarea-autosize/blob/caf00a47fb1cf403ed1874cae9e188d16957051b/src/calculateNodeHeight.js#L66) when we try to assign to `hiddenTextarea.style[key]`, because `hiddenTextarea` is `false`, and `hiddenTextarea.style` is `undefined`.

The crash could probably be avoided by deferring the browser check and `hiddenTextarea` initialization until the first time `calculateNodeHeight` is invoked.

**Comment by Andarist** [comment] 2017-09-19 08:21
Hm, then question is why [`this test`](https://github.com/andreypopp/react-textarea-autosize/blob/8d53e5f18c56f4f2424b47c6571713c43dc55407/src/index.js#L134) allows to proceed. 

According to [my findings](https://github.com/andreypopp/react-textarea-autosize#how-to-test-it-with-jest-and-react-test-renderer) JSDOM alone doesnt provide refs for your components.

**Comment by bryanrsmith** [comment] 2017-09-19 16:08
@Andarist I've revised my comment above with more detailed steps. I'm using JSDOM directly (see code in previous comment) with Enzyme instead of react-test-renderer, so my setup is a little different than what you linked to. As far as I can tell, refs work fine. As I mentioned, if I only run the JSDOM initialization code before importing react-textarea-autosize, everything works well.

**Comment by Andarist** [comment] 2018-07-03 20:31
It seems to me that loading JSDOM before this library is the only reasonable thing to do. Library itself shouldnt handle "environment switching" because it's not a real-life scenario.

**Closed by Andarist** 2018-07-03 20:31 UTC
