### ISSUE TITLE
What files need to be hosted?

### ISSUE THREAD

**Issue by sufuf3** [andreypopp/react-textarea-autosize#132] opened 2017-02-15 13:56 UTC
Hi @andreypopp, 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We want to host this library.
Now I guess the files need to be added in cdnjs as fllowing:

- src/TextareaAutosize.js
- src/calculateNodeHeight.js

Could you please confirm if there is any other files need to be added in cdnjs?
Thank you.

[cdnjs/cdnjs#10364](https://github.com/cdnjs/cdnjs/pull/10364)

**Comment by Andarist** [comment] 2017-04-29 23:10
Closing this as duplicate of #140

**Closed by Andarist** 2017-04-29 23:10 UTC
Labels: enhancement
