### ISSUE TITLE
Hidden textarea width

### ISSUE THREAD

**Issue by gondzo** [andreypopp/react-textarea-autosize#187] opened 2018-01-12 09:19 UTC
Looks like the hidden textarea doesn't respect the width attribute immediately, so the height calculations are off. See this screenshot https://media.giphy.com/media/3ohjUTFNBwe7485jcQ/giphy.gif
I'm not sure about the cause, but setting maxWidth=width to the hidden text area seems to solve it (at https://github.com/andreypopp/react-textarea-autosize/blob/a836fa4e00b4f6885b8593bf65450659200f9197/src/calculateNodeHeight.js#L69 add `hiddenTextarea.style["max-width'] = sizingStyle["width"];`

Maybe there is some css in my app that is causing this, but hidden textarea should ideally have all styles reset first.

**Comment by Andarist** [comment] 2018-01-12 11:14
Are you able to prepare a reproduction case for this?

**Comment by gondzo** [comment] 2018-01-12 13:01
not right away, as I can reproduce only in a specific component, so creating a minimal case will take a while.

**Comment by Andarist** [comment] 2018-07-03 20:31
Closing because original author did not provide enough information to handle this.

**Closed by Andarist** 2018-07-03 20:31 UTC
