### ISSUE TITLE
Non synchronous value sets break cursor position

### ISSUE THREAD

**Issue by jquense** [andreypopp/react-textarea-autosize#68] opened 2015-11-04 11:15 UTC
hi! thanks for the great component,

If you are controlling the component value but don't update the value immediately, the textarea will render a few times between resetting the old value and moving the cursor to the end of the textarea (so start typing in the middle of some text). 

minimal reproducible code below:

``` js
<Textarea 
   value={(this.state || {}).value} 
   onChange={ e => {
     let value = e.target.value;
     setTimeout(() => this.setState({ value }))
  }}
/>
```

You might ask _why_ update the value asynchronously, and that would be a valid question! Some times you don't have a choice, the upper setState _may_ be async, and if you are managing state across Portals/Subtrees/Layers?Whatever-the-current-term-is the additional `ReactDom.render()` is async generally.

I have poked through the code to try and see If anything immediately stood out as the cause of the issue but didn't see anything (due almost certainly to my ignorance), perhaps its due to triggering _resizeComponent in the onChange() handler, maybe it's related to: https://github.com/facebook/react/issues/1698 (tho that is clearly been fixed).

and not to hawk my own wares, but perhaps explicitly managing the controlled/uncontrolled state of the input might help, we use: https://github.com/jquense/uncontrollable for such things.

**Comment by jquense** [comment] 2015-11-04 12:36
__addendum__ this may be a large React bug. https://github.com/facebook/react/issues/5386

Well something is definately causing this behavior in this component but not my other inputs so there is still something specific that this component but the async set may not be the actual issue.

**Comment by sohwendy** [comment] 2015-12-30 03:24
A partial solution is to check if props and states have changed in shouldComponentUpdate. 

This will work for most cases except typing [enter] in the middle of the text.  

Hope to get a better solution

```
    key: 'shouldComponentUpdate',
    value: function shouldComponentUpdate(nextProps, nextState) {
      for (const i in nextProps) {
        if (!(nextProps[i] ==  this.props[i])) {
          return true;
        }
      }
      for (const i in nextState) {
        if (!(nextState[i] == this.state[i])) {
          return true;
        }
      }
      return false;
    }

**Comment by sunjay** [comment] 2016-01-26 21:48
This is the same issue as seen here: https://github.com/reflux/refluxjs/issues/43#issuecomment-92368545

That's a link to a solution as well. Basically what @sohwendy is pointing to.

**Comment by alexfedoseev** [comment] 2016-10-25 15:15
I don't think it has something w/ asynchronicity as I faced this issue w/ non-async code (sync redux action creator). It's a weird bug, b/c I render the same component in another part of the app, but it works fine.

**Comment by HadrienPierart** [comment] 2016-11-02 11:21
Somehow, using the `defaultvalue` prop instead of the `value` prop fixes the issue and the cursor/caret works properly...

**Comment by alexfedoseev** [comment] 2016-11-07 19:13
I figured out what caused my issue: it was `Modal` component from `react-overlays`/`react-bootstrap` + any lib, that is child of `Modal` and is passing value to `input`/`textarea` from its local state. I confirmed this with 2 such libs (this one + my form validator). This case can be reproduced w/ the following scenario:

```js
<Modal>
  <SomeLibThatPassesValueFormItsLocalStateToTextInputOrTextarea>
    <input type="text" value={props.value} />
  </SomeLibThatPassesValueFormItsLocalStateToTextInputOrTextarea>
</Modal>
```

On the props update I observe 2 re-renders in the `input` component: 
* updater triggered
* updated value passed to the root component
* first render w/ obsolete props
* second w/ correct next props

This first render w/ obsolete props is the reason of this issue: input receives outdated (its current) value (at this point cursor is placed correctly), but next async update sets next value, vdom flushes this update and browser resets cursor position.

If I do this:

```js
<SomeLibThatPassesValueFormItsLocalStateToTextInputOrTextarea>
  <Modal>
    <input type="text" value={props.value} />
  </Modal>
</SomeLibThatPassesValueFormItsLocalStateToTextInputOrTextarea>
```

There is only one render per update and everything works as expected.

It's quite late for me today, tomorrow I'll file an issue at `react-overlays`/`react-bootstrap` repo.

**Comment by alexfedoseev** [comment] 2016-11-08 07:46
Issue: https://github.com/react-bootstrap/react-bootstrap/issues/2323

**Comment by dancrew32** [comment] 2017-04-25 00:06
So basically use one or the other. Thanks @HadrienPierart!

```jsx
// Uncontrolled.
<Textarea 
    defaultValue={this.state.foo} 
    onChange={(event) => this.setState({foo: event.target.value})}/>
```

```jsx
// Controlled.
<Textarea value={this.state.foo}/>
```

**Comment by Andarist** [comment] 2017-04-29 23:15
I think there is no more issue here and going to close this now, if something stays unresolved, let me know and I reopen so we can work through it.

**Closed by Andarist** 2017-04-29 23:15 UTC
