### ISSUE TITLE
Problems when using server side rendering

### ISSUE THREAD

**Issue by wamujlb** [andreypopp/react-textarea-autosize#184] opened 2017-12-06 12:42 UTC
I use server side rendering. And on first init the height is much bigger than it has to be. After re-rendering component or window resize it works fine.

**Comment by Andarist** [comment] 2017-12-06 13:00
This component performs DOM measurement to calculate it's height. Obviously this cannot be done on the server, if you are using SSR with this component I'd advise you to pass initial height in [`props.style.height`](https://github.com/andreypopp/react-textarea-autosize/blob/a5a2e099e0e8746e13be96effbaa6399a385ab31/src/index.js#L48)

**Comment by wamujlb** [comment] 2017-12-06 13:04
@Andarist . Can you show me an example of it?

**Comment by Andarist** [comment] 2017-12-06 13:28
Should work, without you sharing the reproduced issue on a standalone repository I won't be able to help you any further.

**Comment by Andarist** [comment] 2018-07-03 20:22
Closing because original author did not provide enough information to handle this.

**Closed by Andarist** 2018-07-03 20:22 UTC

**Comment by f0rmat1k** [comment] 2019-06-19 07:11
@Andarist After SSR i get `height: 0` on textarea. I suppose the reason of this is zero at the end of `height: props.style && props.style.height || 0`. Then on client after rendering i get FOUC of textarea height when 0 becomes some number.

**Comment by Andarist** [comment] 2019-06-19 20:58
That's expected - we can't know the final height automatically without rendering the component first (or without getting it as prop)
