### ISSUE TITLE
Support new React.createRef() function

### ISSUE THREAD

**Issue by acnebs** [andreypopp/react-textarea-autosize#214] opened 2018-07-19 19:37 UTC
This is a new way to handle refs introduced in React 16.3 that is much cleaner and will probably be the supported method going forward, [as seen here.](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs)

`react-textarea-autosize` currently throws a propType error if you try to use a ref Object created by `createRef()` instead of the standard callback ref method.

As a side note, using `innerRef` to pass a ref to the DOM node is much more common than `inputRef` (this is the only project where I've seen `inputRef` used). So it might be nice to change it to innerRef if another breaking change is made.

**Comment by Andarist** [comment] 2018-07-19 21:51
`innerRef`/`inputRef` is really a minor issue - `innerRef` might be somewhat more popular because some libraries have no "default" type of underlaying elements, so the name of the prop has to be type-agnostic. We don't have this problem, so `inputRef` makes sense (not that `innerRef` wouldnt).

As to `createRef` - adding support for it would be either a breaking change (new major version, recently already done it, dont want to make those too often) or would require extra code being added to the library to differentiate `inputRef` type (dont want to increase the library's byte footprint).

`forwardRef` - also a breaking change, breaking backwards compatibility for not really a good enough reason (imho). There are rumours (spread by react core team) that new component API is coming (or at least is being discussed), so I'd like to wait & see how it plays out - maybe then it would be a good thing to migrate to `forwardRef` stuff.

**Comment by rubencodes** [comment] 2018-11-30 14:58
Any update on this? I'd love to be able to use `createRef`!

**Comment by lcsrinaldi** [comment] 2018-11-30 15:31
@Andarist working for me, just tested it. Thanks for adding.

**Comment by Andarist** [comment] 2018-11-30 19:17
Thanks for checking - ill try to remember to release 7.1.0 after the weekend

**Comment by lcsrinaldi** [comment] 2018-11-30 19:41
One thing only. It throws an error if the value is either null or false, undefined works. Not sure if it's the intended behavior. 👍

**Comment by Andarist** [comment] 2018-11-30 23:18
`undefined` causes a default prop to be used which is a noop function, therefore it doesnt throw. I can loosen the restriction and guard against falsy values but Im not sure if I should.

Do you have any real world example in which you'd like to pass `null` or `false`?

**Comment by Andarist** [comment] 2018-12-03 09:09
Released as 7.1.0

**Closed by Andarist** 2018-12-03 09:09 UTC
