### ISSUE TITLE
Importing component error - object

### ISSUE THREAD

**Issue by SavageWilliam** [andreypopp/react-textarea-autosize#159] opened 2017-06-23 18:53 UTC
![image](https://user-images.githubusercontent.com/15717822/27496169-d52db3c0-584c-11e7-971d-e0627f590222.png)

When importing the component with ES6, I'm getting this error in my render method. 

Logging the imported component - the import isn't a class but an object with default property. 

Any suggestions on what I could be doing wrong here? / is there an issue with the export?

![image](https://user-images.githubusercontent.com/15717822/27496329-78ff68b8-584d-11e7-8f58-67d2ef29eded.png)

**Comment by Andarist** [comment] 2017-06-23 19:11
Could u share ur repo or a sample repo with issue reproduced?

**Comment by SavageWilliam** [comment] 2017-06-23 20:44
Can't share the repo, I could try and recreate the environment.

How does the component respond to being passed to Field in redux-form?

**Comment by Andarist** [comment] 2017-06-24 07:57
Would be cool if you can share reproduced environment. Probably it's some configuration issue.

**Comment by d4rkb1ue** [comment] 2017-06-27 09:00
I'm using typescript and also have this problem. But I think the reason isn't the react-textarea-autosize itself. Try to use
```
@types/react-textarea-autosize": "4.0.7",
```

I think the newest type file may cause this problem. Everything goes fine after rollback.

**Comment by ArtyomResh** [comment] 2017-07-27 15:38
I have the same problem, and I can't share project too. Do somebody found solution?

**Comment by Andarist** [comment] 2017-07-27 19:25
You dont have to share the exact project where you are facing the issue. If you can please create a new project with the same configuration (so no business logic included), it would help us to fix it.

**Comment by ArtyomResh** [comment] 2017-07-28 08:22
Sure, I will try on this weekend.

**Comment by Andarist** [comment] 2018-07-03 20:23
Closing because original author did not provide enough information to handle this.

**Closed by Andarist** 2018-07-03 20:23 UTC
