### ISSUE TITLE
Default or Initial Height not working

### ISSUE THREAD

**Issue by critdhenz** [andreypopp/react-textarea-autosize#156] opened 2017-06-01 08:50 UTC
`style={{ resize: 'none', minHeight: 34, height: 34 }}`

Initial height: 34 is not working, the plugin has inline CSS of `height: 38px;

Thanks

**Comment by Andarist** [comment] 2017-06-01 08:57
Could u share reproduced issue on something like codesandbox, so its easier to debug and fix?

**Comment by critdhenz** [comment] 2017-06-01 09:10
`<TextareaAutosize
		name="description"
		rows={1}
		value={data.description}
		style={{ resize: 'none', minHeight: 34, height: 34 }}
/>`

**Comment by Andarist** [comment] 2017-06-01 09:45
What's ur use case?

This feature was introduced to prevent FOUC for server side rendering - more can be read here - https://github.com/andreypopp/react-textarea-autosize/pull/108 .

In the browser environment library is calculating real height asap (in `componentDidMount`) and I cannot really think of now when this would be undesirable.

**Comment by Andarist** [comment] 2017-06-24 08:00
@critdhenz any update on this?

**Comment by FrenchMajesty** [comment] 2017-07-04 22:51
Having the same issue.
I would like my textarea to have a min of 2 rows but the plugin has inline css of "26px" thus reducing it to 1.

**Comment by Andarist** [comment] 2017-07-05 08:34
@FrenchMajesty if you want to have 2 rows initially in your textarea, you should use `minRows` prop instead of using the `style`

**Comment by khrykin** [comment] 2018-02-05 17:29
@Andarist `minRows` isn't respected on the server as well as on the client in case of rendering on top of server-rendered html. `style.height` is respected on the server, but swept away on the client... 

Why not set  actual `<textarea />` `rows` to `props.minRows` intially?  Would solve the problem I guess.  

My current workaround:
```javascript
componentDidMount() {
  this.input.setState({ height: 64 })
}

render() {
  return (
    <Textarea
      ref={n => (this.input = n)}
      style={{ height: 64 }}
      minRows={2}
    />
  )
}
```

**Comment by Andarist** [comment] 2018-02-05 22:41
@khrykin 
> minRows isn't respected on the server as well as on the client in case of rendering on top of server-rendered html.

this is little bit weird - we calculate the height based on minRows in `componentDidMount` which should run on the client. Would you be able to prepare a sample repository with the issue? Would help to understand the problem and fix it.

> Why not set actual <textarea /> rows to props.minRows intially? Would solve the problem I guess.

This is interesting. I've played a little bit with it and seems that it could work, dunno though if browsers are consistent about this.

**Comment by Andarist** [comment] 2018-07-03 20:29
Closing because original author did not provide enough information to handle this.

Second idea (setting rows to minRows) is quite nice, but I don't have time to test it out across browsers. Someone else would have to step up to do it and send up a PR with a change.

**Closed by Andarist** 2018-07-03 20:29 UTC
