### ISSUE TITLE
`NaN` is an invalid value for the `height` css style property

### ISSUE THREAD

**Issue by jeffijoe** [andreypopp/react-textarea-autosize#173] opened 2017-08-11 11:26 UTC
```
`NaN` is an invalid value for the `height` css style property
```

My textarea is invisible initially, and the first render gives that error.

I stepped through the code, and it's a result of `calculateNodeStyling` returning `NaN` props. Perhaps fallback them to 0 to avoid this?

**Comment by Andarist** [comment] 2017-08-11 11:44
Could u share a reproduced issue on something like codesandbox.io ? Should be fairly easy. Also please specify your browser and its version.

**Comment by jeffijoe** [comment] 2017-08-11 12:21
Trying to reproduce, haven't been able to on a sandbox yet, my setup involves portals. 😄 

macOS Sierra, Chrome 60

**Comment by jeffijoe** [comment] 2017-08-11 12:32
Regardless, I think it's better to avoid `NaN` in any case, and a simple `const height = calculated || 0` should do the trick

**Comment by Andarist** [comment] 2017-08-11 12:34
I agree that `NaN` should be avoided, but before changing the code I would like to first understand exact way how it got there.

**Comment by jeffijoe** [comment] 2017-08-11 12:38
![image](https://user-images.githubusercontent.com/2505474/29213251-beebdb56-7ea2-11e7-9336-614a609135c2.png)

Does this help?

**Comment by Andarist** [comment] 2017-08-11 12:51
A little bit, but still cannot reproduce it. Could u list what css styles ur element has when `window.getComputedStyle` is called?

**Comment by jeffijoe** [comment] 2017-08-11 13:10
They are all empty.

![image](https://user-images.githubusercontent.com/2505474/29214318-2ec4e13a-7ea7-11e7-9206-3eff87d701ab.png)

**Comment by Andarist** [comment] 2017-08-11 13:51
I meant CSS rules, not the computed values, sorry for the confusion.

**Comment by jeffijoe** [comment] 2017-08-11 14:00
Copy-pasted from DevTools.

I did notice one odd thing; when inspecting the node in Elements, it did not seem to be mounted in the tree.

```
element.style {
    height: 0px;
}


.Textarea__textarea___1YgWz {
    resize: none;
}

.Input__input___38tDK {
    background-color: #F9FAFC;
    border: 1px solid #e1e6f0;
    -webkit-transition: 0.2s border, 0.2s background-color 0.2s color, 0.2s -webkit-box-shadow;
    transition: 0.2s border, 0.2s background-color 0.2s color, 0.2s -webkit-box-shadow;
    transition: 0.2s border, 0.2s background-color 0.2s color, 0.2s box-shadow;
    transition: 0.2s border, 0.2s background-color 0.2s color, 0.2s box-shadow, 0.2s -webkit-box-shadow;
    display: block;
    font-size: 14px;
    padding: 10px;
    width: 100%;
    outline: none;
    color: #2a292e;
    border-radius: 2px;
}

button, input, select, textarea {
    background-color: transparent;
    border-style: none;
    color: inherit;
}

button, input, optgroup, select, textarea {
    font: inherit;
}

textarea {
    overflow: auto;
    resize: vertical;
}

* {
    padding: 0;
    margin: 0;
}

*, ::before, ::after {
    background-repeat: no-repeat;
    -webkit-box-sizing: inherit;
    box-sizing: inherit;
}
user agent stylesheet
textarea {
    -webkit-appearance: textarea;
    background-color: white;
    -webkit-rtl-ordering: logical;
    user-select: text;
    flex-direction: column;
    resize: auto;
    cursor: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
    border-width: 1px;
    border-style: solid;
    border-color: initial;
    border-image: initial;
    padding: 2px;
}
user agent stylesheet
input, textarea, select, button {
    text-rendering: auto;
    color: initial;
    letter-spacing: normal;
    word-spacing: normal;
    text-transform: none;
    text-indent: 0px;
    text-shadow: none;
    display: inline-block;
    text-align: start;
    margin: 0em;
    font: 11px system-ui;
}
user agent stylesheet
input, textarea, select, button, meter, progress {
    -webkit-writing-mode: horizontal-tb;
}
Inherited from div.Sheet__wrapper___yRDan

.Sheet__wrapper___yRDan {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 100;
    font-size: 14px;
}
Inherited from div.Overlay__root___3TycE.Overlay__fixed___2dtTx.Overlay__hidden___3L3au

.Overlay__hidden___3L3au {
    opacity: 0;
    pointer-events: none;
}
Pseudo ::before element

::before, ::after {
    text-decoration: inherit;
    vertical-align: inherit;
}

*, ::before, ::after {
    background-repeat: no-repeat;
    -webkit-box-sizing: inherit;
    box-sizing: inherit;
}
Pseudo ::after element

::before, ::after {
    text-decoration: inherit;
    vertical-align: inherit;
}

*, ::before, ::after {
    background-repeat: no-repeat;
    -webkit-box-sizing: inherit;
    box-sizing: inherit;
}
Pseudo ::selection element

::selection {
    background-color: #b3d4fc;
    color: #000;
    text-shadow: none;
}
```

**Comment by Andarist** [comment] 2017-08-11 21:54
> I did notice one odd thing; when inspecting the node in Elements, it did not seem to be mounted in the tree.

Thats turbo weird and probably root of the problem. Could u investigate why it got detached?

**Comment by jeffijoe** [comment] 2017-08-11 21:56
It could possibly be due to being unmounted after a route change in react-router.

**Comment by Andarist** [comment] 2017-08-11 22:00
when the parent component unmounts it should also unmount its children (react-textarea-autosize's instance in this case) and call its lifecycle hooks, so this should be cleaned up for u and certainly measuring code shouldnt run

**Comment by jeffijoe** [comment] 2017-08-14 10:16
Sadly I am unable to reproduce it on a CodeSandbox. Regardless, I think it makes sense to add the guards.

**Comment by Andarist** [comment] 2017-08-14 12:43
> Regardless, I think it makes sense to add the guards.

I cannot agree with that statement. Guards should be added for a reason, and until I know the exact reason why they should be added I won't do it. In my opinion such guards can often only obscure the real issue that there is something broken in the application and tracking down the real issue might become really hard or even impossible - or you might not even be aware of the issue, because the error got swallowed silently.

I don't say there is no reason to add them - but like I've said, I would like to know it first. And then I will have a clean conscience about adding them.

**Comment by christopherjbaker** [comment] 2017-12-20 00:51
I am getting the same error during my tests (using Zombie). `hiddenTextarea.scrollHeight` is returning `undefined`.

**Comment by Andarist** [comment] 2017-12-20 00:58
@christopherjbaker could you share a repository with the issue reproduced?

**Comment by BossGrand** [comment] 2018-01-22 08:22
i'm seeing this too

**Comment by jbfm** [comment] 2018-03-20 13:51
I've implemented a PoC here https://codesandbox.io/s/48yjjrxvz0

The issue appears when you use `minRows` and mount it on a DOM node not yet in the tree.

**Comment by rhberro** [comment] 2018-03-21 18:36
I am facing this problem this as well.

**Comment by Andarist** [comment] 2018-03-21 23:12
@jbfm thanks for the repro, gonna certainly create some fallback for the NaN case, but even with one it won't render initial height correctly for ur textarea, because no "trigger" happens for us to recalculate height when you append it to the DOM

In theory we could use MutationObserver to detect this, but seems kinda like an overkill. What's your use case to prerender this without attaching it to the DOM?

**Comment by jeffijoe** [comment] 2018-03-22 08:24
@jbfm Same use case; modal in a portal.

**Comment by Andarist** [comment] 2018-03-22 08:44
Ok, I understand the general use case but still unsure why those modals are rendered in memory if they are not attached to the DOM anyway? Does it give u any benefits?

Just curious, gonna add some guard against it later anyway.

**Comment by jbfm** [comment] 2018-03-22 08:55
Definitely no benefit, simply returning `null` when it isn't open solves this issue.

There are however other usecases I can see, building a complete node before attaching it to the DOM can be more efficient than building it after it's attached, using document fragments for example.

**Comment by Andarist** [comment] 2018-03-23 08:31
I'm only slightly worried that mounting the rendered subtree might not cause a re-render and therefore height won't be recalculated, but gonna wait for an actual report about this before taking any actions against that.

I'll prepare a new release with a guard for this in the weekend.

**Comment by culshaw** [comment] 2018-03-23 11:12
@Andarist I can replicate 100% of the time in a headless DOM. Any way I can provide anymore clarity?

**Comment by Andarist** [comment] 2018-03-25 00:44
I've released a new version, please check it out and report back if you find any issues with it or if it didn't fix your original issue.

Closing as "possibly fixed" but feel free to revive the thread if necessary.

**Closed by Andarist** 2018-03-25 00:44 UTC

**Comment by chrisforrette** [comment] 2019-01-18 23:19
I'm currently on version `7.1.0` and using this in a scenario as described above—rendering the textarea in a modal using a React portal—and I'm not getting the error message but I am getting a `height: 0` set on the input. I wasn't able to reason out a workaround from this thread, but is there anything I need to do aside from having a current version of the package installed?

**Comment by Andarist** [comment] 2019-01-19 08:19
If I understand your problem correctly you need to rerender TextareaAutosize when attaching it to DOM.

**Comment by chrisforrette** [comment] 2019-01-19 23:18
@Andarist Yea, that sounds about right. Would you suggest any particular approach to manually kicking TextareaAutosize to re-render after the modal attachment?

**Comment by alexknipfer** [comment] 2019-01-20 21:43
I'm running into the same area scenario described above when writing a my tests, errors looks like the following:

```
Warning: `NaN` is an invalid value for the `height` css style property.
          in textarea (created by TextareaAutosize)
```

**Comment by Andarist** [comment] 2019-01-21 20:04
Maybe its jsdom bug? Not sure.

> @Andarist Yea, that sounds about right. Would you suggest any particular approach to manually kicking TextareaAutosize to re-render after the modal attachment?

Im not having any particular preference for this, depends on your projects and the code structure.

**Comment by hizegi** [comment] 2020-04-07 00:56
I'd also like to add I get this error while writing my tests. As someone mentioned above, I too am using styled components to style the textarea. Using `border: none` will throw this error. If anyone comes across this, a way to silence this error is to use `border: 0`.
