### ISSUE TITLE
Wrong initial height

### ISSUE THREAD

**Issue by jef-sure** [andreypopp/react-textarea-autosize#93] opened 2016-03-30 18:37 UTC
Initial height is '15px', after I type any symbol, it is set to '26px'. In debugger I see hidden textarea uses initial font-family 'monospace' and after typing any symbol it is changed to 'Helvetica'. I couldn't find a workaround yet.

**Comment by SohKai** [comment] 2016-06-23 10:50
A related issue (or maybe the same) is that the component calculates its initial height immediately on render, so if there's any css is loaded afterwards that changes the layout of the component, it'll have incorrectly calculated its height until it resizes after an action happens.

**Comment by serkandurusoy** [comment] 2016-07-29 17:24
Yeah, this is also a problem for me and it kind of a bad one because I'm styling it with some css transitions that take some time.

It is aesthetically pleasing once initialized, but the initial render is a problem because it transitions from some initial small height into its actual required height, also displaying the scrollbar until initial rendering is complete!

**Comment by machineghost** [comment] 2016-08-25 17:42
I'm not certain, but I faced a similar problem with my textarea not rendering at the correct height initially.

I found the following resolved it:

    render() {
        return <Textarea ref="textarea" />
    }
    componentDidMount() {
        _.defer(() => this.refs.textarea._resizeComponent());
        // NOTE: _.defer comes from Underscore/Lodash
        // _.defer(foo) === window.setTimeout(foo, 1);
    }

In other words, wait for your textarea to get added to the DOM, and then 1ms later (after it's actually part of the DOM and the browser has calculated everything) tell the textarea to recalculate it's height.

In terms of a more permanent fix ...

1) An easy solution is to just remove the "_" from "_resizeComponent" (ie. make it a public method) and tell people to do what I described

2) The component itself could (in its own `componentDidMount`, and possibly in `componentDidUpdate` also) call `_resizeComponent` automatically.  This *seems* safe to do all the time to me, but if not you might want to add a new prop (`resizeAutomatically={true}`) to control it.

**Comment by joetidee** [comment] 2016-09-10 11:36
I had this same problem when I added the 'form-control' calss to the textarea (which is a standard Bootstrap class). This class had the property width: 100%, which when removed allowed the textarea to resize correctly when the textarea was rendered. However, it meant that the textarea width was now not working.
Any way to get around/fix this?

**Comment by machineghost** [comment] 2016-09-12 16:52
@joetidee 

Does your textarea have a ref on it like the one from my `render` method:

    return <Textarea ref="textarea" />

?  If not, that is probably the issue.

**Comment by joetidee** [comment] 2016-09-13 22:20
Yes, I had a ref on it.

**Comment by machineghost** [comment] 2016-09-13 22:32
>Yes, I had a ref on it.

Right, but "a ref" isn't enough: it has to be `ref="textarea"`, or else you also have to modify `this.refs.textarea` to be `this.refs.whateverRefYouUsedForYourTextarea`.

If your `ref` attribute matches your reference to it in `this.refs`, and `this.refs.whatever` is still undefined, your problem is with React, not this library, as under normal circumstances a React component should be able to access its own rendered refs.  If matching refs aren't the problem, perhaps you could paste your code here?

**Comment by joetidee** [comment] 2017-04-29 15:34
Still having issues with this. I have upgraded to the latest version. My textarea is as follows:
```

<TextareaAutosize
     rows={1}
     onChange={this.props.saveSubTitleFunc.bind(this, this.props.blockInstanceId, this.props.subInstanceId)}
     className="title"
     value={this.state.title}
     placeholder="Enter a title..."
/>
```

This textarea is one of many on a tab that is hidden when the page loads - could this be the reason why te height is not auto-adjusting to the contents?

**Comment by Andarist** [comment] 2017-04-30 08:36
@joetidee Could u provide a reproduced issue on something like webpackbin? would help a lot with fixing this

**Comment by joetidee** [comment] 2017-05-02 17:50
That's going to be difficult. I have noticed that when the component that these textareas are in is updated, the textareas resize to how they should be. So, just wondering what that might be (?)

**Comment by Andarist** [comment] 2017-05-02 18:55
Cannot help much without reproduced example :/ otherwise its like searching for a needle in a haystack

**Comment by joetidee** [comment] 2017-05-02 22:49
```
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import AuditTemplateChooser from './AuditTemplateChooser.jsx';
import AuditTemplateQuestion from './AuditTemplateQuestion.jsx';
import TextareaAutosize from 'react-textarea-autosize';
import { updateItemOrderSelectedTemplate, addInsertChooserToSelectedTemplate } from '../actions/selectedTemplateActions.js';
import { closestByClass } from '../helpers/domNav.js';


const mapStateToProps = (state, ownProps) => {return {
    selectedTemplateQuestionData: state.selectedTemplateQuestionData
}};


const mapDispatchToProps = (dispatch, ownProps) => {
    return bindActionCreators({
        updateItemOrderSelectedTemplate,
        addInsertChooserToSelectedTemplate
    }, dispatch)
};


export class AuditTemplateSubheading extends Component {

    constructor(props) {
        super(props);
        this.subVisible = false;
        this.state = {
            title: (this.props.title) ? this.props.title : ""
        };
    }

    componentDidMount(){
        this.initBlockInsertionButtons();
        this.initBlockSettingsButton();

        // Shows chooser if no items exist in the sub-block.
        let items = this.props.items;
        if( items.length === 0 ){
            this.props.addInsertChooserToSelectedTemplate(this.props.blockInstanceId, this.props.subInstanceId, 0);
        }

        this.initTitle();
        this.initSortable();
        this.fadeInSubBlock();
    }

    componentDidUpdate(){
        // Shows chooser if no items exist in the sub-block.
        let items = this.props.items;
        if( items.length === 0 ){
            this.props.addInsertChooserToSelectedTemplate(this.props.blockInstanceId, this.props.subInstanceId, 0);
        }

        this.initTitle();
        this.initSortable();
        this.fadeInSubBlock();
    }

    initBlockInsertionButtons(){
        let subInstanceId = this.props.subInstanceId;

        let el = document.querySelector('[data-instance-id="' + subInstanceId + '"] > .insert-object-block-top .left a');
        if(el) {
            let iobt = closestByClass(el, "insert-object-block-top");
            el.removeEventListener("mouseover");
            el.addEventListener("mouseover", function () {
                if(iobt){ iobt.classList.add("over"); }
            });
            el.removeEventListener("mouseout");
            el.addEventListener("mouseout", function () {
                if(iobt){ iobt.classList.remove("over"); }
            });
        }

        el = document.querySelector('[data-instance-id="' + subInstanceId + '"] > .insert-object-block-bottom .left a');
        if(el) {
            let iobb = closestByClass(el, "insert-object-block-bottom");
            el.removeEventListener("mouseover");
            el.addEventListener("mouseover", function () {
                if(iobb){ iobb.classList.add("over"); }
            });
            el.removeEventListener("mouseout");
            el.addEventListener("mouseout", function () {
                if(iobb){ iobb.classList.remove("over"); }
            });
        }
    }

    initBlockSettingsButton(){
        let subInstanceId = this.props.subInstanceId;
        let el = document.querySelector('[data-instance-id="' + subInstanceId + '"] > .sub-block-padder > .sub-block-padder-inner > .header .right a');
        if(el){
            let sbc = closestByClass(el, "sub-block-container");
            el.removeEventListener("mouseover");
            el.addEventListener("mouseover", function () {
                if(sbc){ sbc.classList.add("over"); }
            });
            el.removeEventListener("mouseout");
            el.addEventListener("mouseout", function () {
                if(sbc){ sbc.classList.remove("over"); }
            });
        }
    }

    fadeInSubBlock(){
        let el = document.querySelector('[data-instance-id="' + this.props.subInstanceId + '"]');
        if(this.subVisible === false && el ) {
            this.subVisible = true;
            //el.style.display="inline";
            //el.style.transition="opacity 2s";
            //el.style.opacity=1;
            //$(el).fadeIn(500, function(){});
            el.classList.add('fade-in');
        }
    }

    initSortable(){
        let self = this;

        $("." + this.props.subInstanceId + " .sub-block-padder .sub-block-padder-inner > .content").sortable({
            axis: "y",
            connectWith: ".template-block-wrapper .template-block-padder .template-block > .content, .sub-block-container .sub-block-padder .sub-block-padder-inner > .content",
            handle: ".item-drag",
            helper: function(event, ui){
                let $clone = $("<div></div>");
                return $clone.get(0);
            },
            items: "> .block-item",
            out: function(event, ui){
                ui.placeholder.removeClass("audit-sortable-placeholder-no-sort");
            },
            over: function(event, ui){
                // Hides placeholder if the item is a sub-block.
                if ( ui.item.hasClass('sub-block-container') ) {
                    ui.placeholder.addClass("audit-sortable-placeholder-no-sort");
                }
                else{
                    ui.placeholder.removeClass("audit-sortable-placeholder-no-sort");
                }
            },
            placeholder: "audit-sortable-placeholder",
            receive: function(event, ui){
                // Prevents a sub-block being dragged into sub-block.
                if ( ui.item.hasClass('sub-block-container') ) {
                    ui.sender.sortable("cancel");
                }
            },
            start: function(event, ui){
                $(".template-container .insert-object-block, .template-container .q-settings-container, .template-container .insert-block").css("visibility","hidden");
                $(".template-container .insert-object-line-block .middle .line").css("visibility","hidden");

                // Sets the fromBlockInstanceId variable.
                let blockObj = ui.item.closest(".template-block-wrapper");
                this.fromBlockInstanceId = $(blockObj[0]).attr("data-instance-id");

                // Sets the fromSubInstanceId variable, if applicable.
                this.fromSubInstanceId = null;
                let subObj = ui.item.closest(".sub-block-container");
                if(typeof subObj[0] !== "undefined") {
                    this.fromSubInstanceId = $(subObj[0]).attr("data-instance-id");
                }
            },
            stop: function(event, ui){
                // Make call to update state.
                let typeBeingOrdered, idBeingOrdered, fromBlockInstanceId, fromSubInstanceId, toBlockInstanceId, toSubInstanceId;
                if(ui.item.hasClass("q-block-container")){
                    typeBeingOrdered = "question";
                }
                else if(ui.item.hasClass("sub-block-container")){
                    typeBeingOrdered = "sub";
                }

                // Get idBeingOrdered.
                idBeingOrdered = $(ui.item[0]).attr("data-instance-id");

                // Get fromBlockId.
                fromBlockInstanceId = this.fromBlockInstanceId;

                // Get fromSubId.
                fromSubInstanceId = this.fromSubInstanceId;

                // Get toBlockId.
                let blockObj = ui.item.closest(".template-block-wrapper");
                toBlockInstanceId = $(blockObj[0]).attr("data-instance-id");

                // Get toSubId.
                let toSubId = null;
                let subObj = ui.item.closest(".sub-block-container");
                if(typeof subObj[0] !== "undefined") {
                    toSubId = $(subObj[0]).attr("data-instance-id");
                }

                // Get newPos.
                let newPos = null;
                if(toSubInstanceId !== null) {
                    newPos = $("." + toSubInstanceId + " .sub-block-padder .sub-block-padder-inner > .content > .block-item").index($("." + toSubInstanceId + " .sub-block-padder .sub-block-padder-inner > .content > ." + idBeingOrdered));
                }
                else{
                    newPos = $("." + toBlockInstanceId + " .template-block-padder .template-block > .content > .block-item").index($("." + toBlockInstanceId + " .template-block-padder .template-block > .content > ." + idBeingOrdered));
                }

                // Cancel sort..
                $(this).sortable('cancel');

                // Make insertion icons visible again.
                $(".template-container .insert-object-block, .template-container .q-settings-container, .template-container .insert-block").css("visibility", "visible");
                $(".template-container .insert-object-line-block .middle .line").css("visibility", "visible");

                // Update blocks state.
                self.props.updateItemOrderSelectedTemplate(typeBeingOrdered, idBeingOrdered, fromBlockInstanceId, fromSubInstanceId, toBlockInstanceId, toSubInstanceId, newPos);
            },
            tolerance: "pointer"
        });
    }

    componentWillReceiveProps(nextProps) {
        this.setState({title: nextProps.title});
    }

    initTitle(){
        let el = document.querySelector('[data-instance-id="' + this.props.subInstanceId + '"] > .sub-block-padder .sub-block-padder-inner > .header .table-row .right textarea');
        if(el) {
            el.removeEventListener("focus");
            el.addEventListener("focus", function(e){
                e.preventDefault();
                el.classList.add("editable");
            });
            el.removeEventListener("blur");
            el.addEventListener("blur", function(e){
                e.preventDefault();
                el.classList.remove("editable");
            });
            el.removeEventListener("click");
            el.addEventListener("click", function(e){
                e.preventDefault();
                e.stopPropagation();
                el.focus();
            });
            el.removeEventListener("keypress");
            el.addEventListener("keypress", function(e){
                if ( e.which === 13 ){
                    return false;
                }
            });
        }
    }

    getSubItems(){
        let subItems = [];
        let items = this.props.items;
        let questionCounter = this.props.questionNum;
        let itemOrder = 0;
        for (let i = 0; i < items.length; i++) {
            if (items[i].type === "question") {

                let questionText;
                let questionTypeId;
                let answerFormat;
                let scaleId;
                let questionAnswers = [];
                let record = this.props.selectedTemplateQuestionData.questionData.filter((obj) => {
                    return obj._id === items[i].questionId;
                });
                if( record !== null && typeof record !== "undefined" && typeof record[0] !== "undefined" ){
                    questionText = record[0].questionText;
                    questionTypeId = record[0].questionType.id;
                    answerFormat = record[0].answerFormat;
                    questionAnswers = record[0].answers;
                    scaleId = record[0].answerScale;
                }

                let item = ( <AuditTemplateQuestion
                    key={items[i].instanceId}
                    questionId={items[i].questionId}
                    questionText={questionText}
                    questionTypeId={questionTypeId}
                    answerFormat={answerFormat}
                    questionAnswers={questionAnswers}
                    scaleId={scaleId}
                    questionInstanceId={items[i].instanceId}
                    blockInstanceId={this.props.blockInstanceId}
                    subInstanceId={this.props.subInstanceId}
                    questionNum={questionCounter}
                    itemOrder={itemOrder}
                    scales={this.props.scales}
                /> );
                subItems.push(item);
                questionCounter++;
                itemOrder++;
            }
            else if (items[i].type === "chooser") {
                let item = ( <AuditTemplateChooser
                    key={items[i].chooserId}
                    removeChooserFunc={this.props.removeChooserFunc.bind(this)}
                    addSubBlockFunc={this.props.addSubBlockFunc.bind(this)}
                    blockInstanceId={this.props.blockInstanceId}
                    subInstanceId={this.props.subInstanceId}
                    chooserId={items[i].chooserId}
                    itemOrder={itemOrder}
                /> );
                subItems.push(item);
                itemOrder++;
            }
        }
        return subItems;
    }

    render(){
        return (
            <div className={this.props.subInstanceId + " clearfix block-item sub-block-container"} data-instance-id={this.props.subInstanceId} >

                <div className="insert-object-block insert-object-block-top">
                    <div className="insert-object-button-block">
                        <div className="left">
                            <div className="circle" />
                            <a title="Insert an item into this Block" onClick={() => {this.props.addInsertChooserToSelectedTemplate(this.props.blockInstanceId, null, this.props.itemOrder);}}
                               className="insert-object-button icon-tidee-add-circled" />
                        </div>
                        <div className="middle">
                            <div className="line" />
                        </div>
                        <div className="right">
                            <div className="no-line" />
                            <div className="line-container">
                                <div className="line" />
                            </div>
                        </div>
                        <div className="right-sub">
                            <div className="no-line" />
                            <div className="line-container">
                                <div className="line" />
                            </div>
                        </div>
                    </div>
                    <div className="insert-object-line-block">
                        <div className="middle">
                            <div className="line" />
                        </div>
                    </div>
                </div>

                <div className="sub-block-padder">
                    <div className="sub-block-padder-inner">
                        <div className="header">

                            <div className="settings-block">
                                <div className="left">
                                    <div className="no-line" />
                                    <div className="line-container">
                                        <div className="line" />
                                    </div>
                                </div>
                                <div className="middle">
                                    <div className="line" />
                                </div>
                                <div className="right">
                                    <a onClick={this.props.removeSubFunc.bind(this, this.props.blockInstanceId, this.props.subInstanceId)}
                                       className="settings icon-tidee-trash-circled remove-block-button"
                                       title="Remove this Sub-block" />
                                </div>
                            </div>

                            <div className="table-row">
                                <div className="left"><div className="item-drag" /></div>
                                <div className="right">
                                    <TextareaAutosize
                                        rows={1}
                                        onChange={this.props.saveSubTitleFunc.bind(this, this.props.blockInstanceId, this.props.subInstanceId)}
                                        className="title"
                                        value={this.state.title}
                                        placeholder="Enter a title..."
                                    />
                                </div>
                            </div>
                        </div>
                        <div className="content">
                            {this.getSubItems()}
                        </div>
                    </div>
                </div>

                <div className="insert-object-block insert-object-block-bottom">
                    <div className="insert-object-button-block">
                        <div className="left">
                            <div className="circle" />
                            <a title="Insert an item into this Block" onClick={() => {this.props.addInsertChooserToSelectedTemplate(this.props.blockInstanceId, null, (this.props.itemOrder+1));}}
                               className="insert-object-button icon-tidee-add-circled" />
                        </div>
                        <div className="middle">
                            <div className="line" />
                        </div>
                        <div className="right">
                            <div className="no-line" />
                            <div className="line-container">
                                <div className="line" />
                            </div>
                        </div>
                        <div className="right-sub">
                            <div className="no-line" />
                            <div className="line-container">
                                <div className="line" />
                            </div>
                        </div>
                    </div>
                    <div className="insert-object-line-block">
                        <div className="middle">
                            <div className="line" />
                        </div>
                    </div>
                </div>

            </div>
        );
    }
}
AuditTemplateSubheading.propTypes = {
    blockId: PropTypes.string,
    subId: PropTypes.string,
    blockInstanceId: PropTypes.string,
    subInstanceId: PropTypes.string,
    title: PropTypes.string,
    itemOrder: PropTypes.number,
    items: PropTypes.arrayOf(PropTypes.object),
    saveSubTitleFunc: PropTypes.func,
    removeSubFunc: PropTypes.func,
    removeChooserFunc: PropTypes.func,
    addSubBlockFunc: PropTypes.func,
    questionNum: PropTypes.number,
    scales: PropTypes.array,
    scaleId: PropTypes.string
};

export default connect(mapStateToProps,mapDispatchToProps)(AuditTemplateSubheading);
```

**Comment by Andarist** [comment] 2017-05-20 10:07
@joetidee sorry for the long response, ive missed ur answer somehow

i cannot quite run ur code as its missing imported modules, could u reproduce the whole issue on something like codesandbox.io?

**Comment by Andarist** [comment] 2017-06-01 09:49
@joetidee @jef-sure 
any update on this?

**Comment by jef-sure** [comment] 2017-06-01 10:15
I identified the problem and made my own such a module :) In short: the component should be re-rendered in `componentDidMount`. I did it via `setState`. https://github.com/jef-sure/pef-chat-demo/blob/master/frontend/src/components/TextareaAutoSize.jsx

**Comment by Andarist** [comment] 2017-06-01 14:16
We do it in [`componentDidMount`](https://github.com/andreypopp/react-textarea-autosize/blob/e613c77e150c11b61d86f9bd3dff5f1406a2e15f/src/index.js#L83) as well, it could have changed though during some recent development.

I'll wait a moment for @joetidee's feedback and close the issue if we cannot get any more data for the moment.

**Comment by joetidee** [comment] 2017-06-03 16:23
OK, I don't have any feedback. It seems to be auto-resixing correctly now, but haven't changed anything directly with the TextareaAutoSize component.

**Comment by Andarist** [comment] 2017-06-03 16:43
Ok,i hope everything is working fine. Closing this then for now

**Closed by Andarist** 2017-06-03 16:43 UTC

**Comment by AlonMiz** [comment] 2021-11-19 08:57
it's a race condition. if the browser was able to download the fonts before the component is ready, the height will be accurate.
but if the fonts are late, and the component did render before the fonts are ready, the height will be off.
several solutions:
1. Wait for the fonts to load, by setting them as a synchronously part of the header
2. rerender the component when you think the fonts will be ready

**Comment by ashiqdey** [comment] 2022-07-18 06:54
For me both for both the case as below are rendering wrong height may be its considering padding and margin of form-group class. Any increment/ decrement variation factor would be better, like `variation="-10px"` so it will add -10px to original height to achieve the height I want.

```
import TextareaAutosize from '@mui/material/TextareaAutosize';

<TextareaAutosize
  placeholder="Press enter for multi line..."
  minRows={1}
  className="form-control"
/>

<Form.Control
  as={TextareaAutosize}
  placeholder="Press enter for multi line..."
  minRows={1}
/>
```

**Comment by Andarist** [comment] 2022-07-18 07:27
`@mui/material/TextareaAutosize` is their own implementation - it's not using this package.
